#version 430 core

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (rgba32f, binding = 0) uniform image2D imageIn;
layout (rgba32f , binding = 1) uniform image2D imageOut;

const int SampleRange = 1;

uniform int PPframeIndex;

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);

    vec3 AccumulatedColor = imageLoad(imageIn, pix).rgb / PPframeIndex;

    imageStore(imageOut, pix, vec4(sqrt(AccumulatedColor), 1.0));
}