#version 430 core
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D img;
const float pi = 3.14159265359;
const int maxBounces = 5;
/*
    Material type indeces.
    1 Lambertian
    2 Metal
    3 Dialectric
*/



struct ModelAABB
{
    vec4 min;
    vec4 max;
    int nodeA;
    int nodeB;
    int triIndex;
    int triCount;
};

//vec4 for good alignment
struct Triangle
{
    vec4 a;
    vec4 b;
    vec4 c;
};


layout (binding = 2, std430) readonly buffer AABBData
{
    ModelAABB aabbs[];
};

layout(binding = 1, std430) readonly buffer VerticesSSBO
{
    Triangle tris[];
};

struct ModelInfo
{
    mat4 matrixModel;
    mat4 invMatrixModel;
    int matIndex;
};

struct material
{
    int materialType;
    vec3 albedo;
    vec3 emmColor;
    float metallic;
    float roughness;
};
struct sphere 
{
    vec3 point;
    float radius;
    int matIndex;
};
struct ray
{
    vec3 dir;
    vec3 pos;
};

struct hitInfo
{
    float dist;
    vec3 normal;
    int matIndex;
};


//Scene Vars
uniform ModelInfo modelsInfo[24];


uniform int ModelAABBIdxs[20];
uniform int modelAABBCount;
uniform float AR;
uniform float tfov;
uniform int uframe;
uniform vec3 CamPos;
uniform material materials[10];
uniform int TriCount;
uniform mat4 InvProj;
uniform mat4 InvView;
uniform int skyColor;


uint PCGHash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float RandomFloat(inout uint seed)
{
    seed = PCGHash(seed);
    return float(seed) / 4294967295.0;
}

vec3 RandomVec3(inout uint seed)
{
    return vec3(
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0);
}

vec3 RandomOnHemisphere(inout uint seed, vec3 normal)
{
    vec3 vector = RandomVec3(seed);
    if(dot(vector, normal) > 0)
    {
        return vector;
    }else
    {
        return -vector;
    }
}


void hitTriangle(ray r, int i, inout hitInfo info)
{
    Triangle tri = tris[i];

    Triangle transformedTri;
    transformedTri.a = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.a.x, tri.a.y, tri.a.z), 1.0)), tri.a.w);
    transformedTri.b = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.b.x, tri.b.y, tri.b.z), 1.0)), tri.a.w);
    transformedTri.c = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.c.x, tri.c.y, tri.c.z), 1.0)), tri.a.w);
    tri = transformedTri;
    vec3 e1 = tri.b.xyz - tri.a.xyz;
    vec3 e2 = tri.c.xyz - tri.a.xyz;
    vec3 p = cross(r.dir, e2);
    float det = dot(e1, p);

    if(abs(det) < 1e-6) return;

    float invDet = 1.0 / det;
    vec3 t = r.pos - tri.a.xyz;
    float u = dot(t, p) * invDet;
    if(u < 0 || u > 1) return;

    vec3 q = cross(t, e1);
    float v = dot(r.dir, q) * invDet;
    if(v < 0 || u + v > 1) return;

    float dist = dot(e2, q) * invDet;
    if(dist > 0.001 && dist < info.dist)
    {
        info.dist = dist;
        info.normal = normalize(cross(e1, e2));
        info.matIndex = modelsInfo[int(tri.a.w)].matIndex;
    }
}

bool AabbRayIntersection(ray r, int idx)
{

    ModelAABB aabb = aabbs[idx];
    vec3 bmin = vec3(aabb.min);
    vec3 bmax = vec3(aabb.max);
    mat4 invModel = modelsInfo[int(aabb.min.w)].invMatrixModel;
    r.pos = (invModel * vec4(r.pos, 1.0)).xyz;
    r.dir = (mat3(invModel) * r.dir);

    vec3 invDir = 1.0 / r.dir;

    vec3 t0 = (bmin - r.pos) * invDir;
    vec3 t1 = (bmax - r.pos) * invDir;

    vec3 tmin = min(t0, t1);
    vec3 tmax = max(t0, t1);

    float tNear = max(max(tmin.x, tmin.y), tmin.z);
    float tFar  = min(min(tmax.x, tmax.y), tmax.z);



    return tFar >= max(tNear, 0.0);
}


const int STACK_SIZE = 32;

struct Stack {
    int data[STACK_SIZE];
    int sp; // stack pointer
};

void stackInit(inout Stack s) {
    s.sp = 0;
}

bool stackEmpty(Stack s) {
    return s.sp == 0;
}

bool stackPush(inout Stack s, int value) {
    if (s.sp >= STACK_SIZE) return false; // overflow
    s.data[s.sp++] = value;
    return true;
}

bool stackPop(inout Stack s, out int value) {
    if (s.sp <= 0) return false; // underflow
    value = s.data[--s.sp];
    return true;
}


void CheckAabbsIntersections(ray r, int starIdx, inout hitInfo HitInfo)
{
    Stack stack;
    stackInit(stack);
    stackPush(stack, starIdx);


    int aabbIdx;
    while(!stackEmpty(stack))
    {
        stackPop(stack, aabbIdx);
        if(aabbs[aabbIdx].triCount == 0)
        {
            if(AabbRayIntersection(r, aabbs[aabbIdx].nodeA))
            {
                stackPush(stack, aabbs[aabbIdx].nodeA);
            }
            if(AabbRayIntersection(r, aabbs[aabbIdx].nodeB))
            {
                stackPush(stack, aabbs[aabbIdx].nodeB);
            }
        }else
        {
            for(int i = aabbs[aabbIdx].triIndex; i < aabbs[aabbIdx].triIndex + aabbs[aabbIdx].triCount; i++)
            {
                hitTriangle(r, i, HitInfo);
            }
        }
    }
}

hitInfo GetHitInfoAABB(ray r)
{
    hitInfo HitInfo;
    HitInfo.dist = 1e30;
    HitInfo.matIndex = -1;
    for(int i = 0; i < modelAABBCount; i++)
    {
        CheckAabbsIntersections(r, ModelAABBIdxs[i], HitInfo);
    }
    return HitInfo;
}
hitInfo GetHitInfo(ray r)
{
    hitInfo HitInfo;
    HitInfo.dist = 1e30;
    HitInfo.matIndex = -1;
    for(int i = 0; i < TriCount; i++)
    {
        hitTriangle(r, i, HitInfo);
    }
    return HitInfo;
}

float ScatteringPdf(vec3 scatDir, vec3 n)
{
    float cosine = dot(scatDir, n);
    return cosine < 0 ? 0 : cosine / pi;
}



vec3  RandomCosineDir(inout uint seed, vec3 w)
{
    float r1 = RandomFloat(seed);
    float r2 = RandomFloat(seed);
    float z = sqrt(1-r2);
    float phi = 2 * pi * r1;
    float sqrtR2 = sqrt(r2);
    float x = cos(phi) * sqrtR2;
    float y = sin(phi) * sqrtR2;


    vec3 axis[3];
    axis[2] = normalize(w);
    vec3 a = (abs(axis[2].x) > 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1, 0, 0);
    axis[1] = normalize(cross(axis[2], a));
    axis[0] = cross(axis[2], axis[1]);

    return axis[0] * x + axis[1] * y + axis[2] * z; 
}

float CosinePdf(vec3 dir, vec3 n)
{
    float cosine = dot(normalize(dir), n);
    return max(0, cosine/ pi);
}

// float GGXNDF(vec3 wm, vec3 n, float a)
// {
//     float NoM = max(dot(n, wm), 0.0);
//     if (NoM <= 0.0) return 0.0;

//     float a2 = a * a;
//     float denom = NoM * NoM * (a2 - 1.0) + 1.0;

//     return a2 / (pi * denom * denom);
// }
float GGXNDF(vec3 wm, float a)
{
    float costheta2 = wm.z * wm.z;
    float tantheta2 = -1.0 + 1.0 / costheta2;
    float denom = pi * costheta2 * costheta2 * pow((a*a + tantheta2), 2.0);
    return a*a / denom; 
}
vec3 Fresnel(vec3 wi, vec3 wm, vec3 f0)
{
    return f0 + (1-f0) * pow(1.0 -  dot(wi, wm), 5.0);
}
float lambda(vec3 w, vec3 n, float a)
{
    float costheta2 = dot(w, n);
    costheta2 *= costheta2;
    float tantheta2 = -1.0 + 1.0 / costheta2;
    return 0.5 * (sqrt(1.0 + a*a*tantheta2) - 1.0);
}
vec3 RandomWm(inout uint seed, vec3 w, float a)
{
    float r1 = RandomFloat(seed);
    float r2 = RandomFloat(seed);
    float thetam = atan(a * sqrt(r1 / (1 - r1)));
    float phim = 2 * pi * r2;
    float x = sin(thetam) * cos(phim);
    float y = sin(thetam) * sin(phim);
    float z = cos(thetam);


    vec3 axis[3];
    axis[2] = normalize(w);
    vec3 an = (abs(axis[2].x) > 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1, 0, 0);
    axis[1] = normalize(cross(axis[2], an));
    axis[0] = cross(axis[2], axis[1]);

    return axis[0] * x + axis[1] * y + axis[2] * z; 

}
float TorSpPdf(vec3 wo, vec3 wm, vec3 n, float a)
{
    float D = GGXNDF(wm, a);
    float cosThetaM = max(dot(n, wm), 0.0);
    float cosWoWm = max(dot(wo, wm), 0.0);

    return (D * cosThetaM) / (4.0 * cosWoWm);
}
float G(vec3 wo, vec3 wi, vec3 n, float a)
{
    return (1 / (1 + lambda(wo,n, a) + lambda(wi,n, a)));
}
void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(img);

    float u = (float(pix.x) + 0.5) / float(size.x);
    float v = (float(pix.y) + 0.5) / float(size.y);

    u = u * 2.0 - 1.0;
    v = v * 2.0 - 1.0;

    vec4 target = InvProj * vec4(u, v , 1.0, 1.0);

    ray r;
    r.dir = vec3(InvView * vec4(normalize(vec3(target) / target.w), 0));
    r.pos = CamPos;

    vec3 rayTraversalInfo = vec3(1.0);
    vec3 rayColor = vec3(0.0);
    uint seed =
    uint(pix.x) * 1973u +
    uint(pix.y) * 9277u +
    uframe  * 26699u + 1u;
    for(int bounces = 0; bounces < maxBounces; bounces++)
    {

        hitInfo HitInfo = GetHitInfoAABB(r);
        // if nothing got hit, just return a base color.
        if (HitInfo.matIndex == -1) {
            if(skyColor == 1)
            {
                float a = 0.5*(r.dir.y + 1);  
                vec3 sky = (1-a)*vec3(1) + a * vec3(0.5, 0.7, 1.0);
                rayColor = rayTraversalInfo * sky;  // environment brightness
            }
            break;
        }

        //Something got hit.
        vec3 HitPoint = r.pos + r.dir * HitInfo.dist;
        vec3 outwardN = HitInfo.normal;
        bool frontFace = dot(r.dir, outwardN) < 0.0;
        vec3 n = frontFace ? outwardN : -outwardN;
        material hitMat = materials[HitInfo.matIndex];

        r.pos = HitPoint + n * 0.001;

        float a  = hitMat.roughness;
        vec3 wo = normalize(-r.dir);
        vec3 wm = RandomWm(seed, n, a);
        vec3 wi = -wo + 2.0 * dot(wo, wm) * wm;
        if(dot(wi, n) <= 0.0 || dot(wo, n) <= 0.0)
            continue;

        vec3 f0 = mix(vec3(1.0), hitMat.albedo, hitMat.metallic);
        float NoV = max(dot(n, wo), 0.0);
        float NoL = max(dot(n, wi), 0.0);

        vec3 brdf = GGXNDF(wm, a)
                * Fresnel(wi, wm, f0)
                * G(wo, wi, n, a)
                / (4.0 * NoV * NoL);
        float pdf = TorSpPdf(wo, wm,n,a);
        vec3 mSample = brdf * NoL / pdf;


        r.dir = wi;
        rayTraversalInfo *= mSample;
        rayColor += rayTraversalInfo * hitMat.emmColor;
    }
    vec4 prev = imageLoad(img, pix);

    imageStore(img, pix, vec4(prev.rgb + rayColor, 1.0));
}