#version 430 core
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D img;
const float pi = 3.14159265359;
const int maxIter = 10;
const int maxBounces = 5;
/*
    Material type indeces.
    1 Lambertian
    2 Metal
    3 Dialectric
*/



struct ModelAABB
{
    vec4 min;
    vec4 max;
    int nodeA;
    int nodeB;
    int triIndex;
    int triCount;
};

//vec4 for good alignment
struct Triangle
{
    vec4 a;
    vec4 b;
    vec4 c;
};


layout (binding = 2, std430) readonly buffer AABBData
{
    ModelAABB aabbs[];
};

layout(binding = 1, std430) readonly buffer VerticesSSBO
{
    Triangle tris[];
};

struct ModelInfo
{
    mat4 matrixModel;
    int matIndex;
};

struct material
{
    int materialType;
    vec3 albedo;
    vec3 emmColor;
    float fuzz;
    float refractionIndex;
};
struct sphere 
{
    vec3 point;
    float radius;
    int matIndex;
};
struct ray
{
    vec3 dir;
    vec3 pos;
};

struct hitInfo
{
    float dist;
    vec3 normal;
    int matIndex;
};


//Scene Vars
uniform ModelInfo modelsInfo[24];


uniform int ModelAABBIdxs[20];
uniform float AR;
uniform float tfov;
uniform vec3 CamPos;
uniform material materials[10];
uniform int TriCount;
uniform mat4 InvProj;
uniform mat4 InvView;
uniform int skyColor;


uint PCGHash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float RandomFloat(inout uint seed)
{
    seed = PCGHash(seed);
    return float(seed) / 4294967295.0;
}

vec3 RandomVec3(inout uint seed)
{
    return vec3(
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0);
}

vec3 RandomOnHemisphere(inout uint seed, vec3 normal)
{
    vec3 vector = RandomVec3(seed);
    if(dot(vector, normal) > 0)
    {
        return vector;
    }else
    {
        return -vector;
    }
}


void hitTriangle(ray r, int i, inout hitInfo info)
{
    Triangle tri = tris[i];

    Triangle transformedTri;
    transformedTri.a = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.a.x, tri.a.y, tri.a.z), 1.0)), tri.a.w);
    transformedTri.b = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.b.x, tri.b.y, tri.b.z), 1.0)), tri.a.w);
    transformedTri.c = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.c.x, tri.c.y, tri.c.z), 1.0)), tri.a.w);
    tri = transformedTri;
    vec3 e1 = tri.b.xyz - tri.a.xyz;
    vec3 e2 = tri.c.xyz - tri.a.xyz;
    vec3 p = cross(r.dir, e2);
    float det = dot(e1, p);

    if(abs(det) < 1e-6) return;

    float invDet = 1.0 / det;
    vec3 t = r.pos - tri.a.xyz;
    float u = dot(t, p) * invDet;
    if(u < 0 || u > 1) return;

    vec3 q = cross(t, e1);
    float v = dot(r.dir, q) * invDet;
    if(v < 0 || u + v > 1) return;

    float dist = dot(e2, q) * invDet;
    if(dist > 0.001 && dist < info.dist)
    {
        info.dist = dist;
        info.normal = normalize(cross(e1, e2));
        info.matIndex = modelsInfo[int(tri.a.w)].matIndex;
    }
}


hitInfo GetHitInfo(ray r)
{
    hitInfo HitInfo;
    HitInfo.dist = 1e30;
    HitInfo.matIndex = -1;
    for(int i = 0; i < TriCount; i++)
    {
        hitTriangle(r, i, HitInfo);
    }
    return HitInfo;
}

float ScatteringPdf(vec3 scatDir, vec3 n)
{
    float cosine = dot(scatDir, n);
    return cosine < 0 ? 0 : cosine / pi;
}

vec3 FresnelRefl(float cosTheta, vec3 eta, vec3 k)
{
    cosTheta = clamp(cosTheta, 0.0, 1.0);

    vec3 cos2 = vec3(cosTheta * cosTheta);
    vec3 sin2 = vec3(1.0) - cos2;

    vec3 eta2 = eta * eta;
    vec3 k2 = k * k;

    vec3 t0 = eta2 - k2 - sin2;
    vec3 a2plusb2 = sqrt(t0 * t0 + 4.0 * eta2 * k2);

    vec3 t1 = a2plusb2 + cos2;
    vec3 a = sqrt(0.5 * (a2plusb2 + t0));
    vec3 t2 = 2.0 * cosTheta * a;

    vec3 Rs = (t1 - t2) / (t1 + t2);

    vec3 t3 = cos2 * a2plusb2 + sin2 * sin2;
    vec3 t4 = t2 * sin2;

    vec3 Rp = Rs * (t3 - t4) / (t3 + t4);

    return 0.5 * (Rp + Rs);

}


vec3  RandomCosineDir(inout uint seed, vec3 w)
{
    float r1 = RandomFloat(seed);
    float r2 = RandomFloat(seed);
    float z = sqrt(1-r2);
    float phi = 2 * pi * r1;
    float sqrtR2 = sqrt(r2);
    float x = cos(phi) * sqrtR2;
    float y = sin(phi) * sqrtR2;


    vec3 axis[3];
    axis[2] = normalize(w);
    vec3 a = (abs(axis[2].x) > 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1, 0, 0);
    axis[1] = normalize(cross(axis[2], a));
    axis[0] = cross(axis[2], axis[1]);

    return axis[0] * x + axis[1] * y + axis[2] * z; 
}

float CosinePdf(vec3 dir, vec3 n)
{
    float cosine = dot(normalize(dir), n);
    return max(0, cosine/ pi);
}

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(img);

    float u = (float(pix.x) + 0.5) / float(size.x);
    float v = (float(pix.y) + 0.5) / float(size.y);

    u = u * 2.0 - 1.0;
    v = v * 2.0 - 1.0;

    vec4 target = InvProj * vec4(u, v , 1.0, 1.0);

    vec3 finalColor = vec3(0.0);
    for(int iter = 0; iter < maxIter; iter++)
    {
        ray r;
        r.dir = vec3(InvView * vec4(normalize(vec3(target) / target.w), 0));
        r.pos = CamPos;

        vec3 rayTraversalInfo = vec3(1.0);
        vec3 rayColor = vec3(0.0);
        uint seed =
        uint(pix.x) * 1973u +
        uint(pix.y) * 9277u +
        iter  * 26699u + 1u;
        for(int bounces = 0; bounces < maxBounces; bounces++)
        {

            hitInfo HitInfo = GetHitInfo(r);
            // if nothing got hit, just return a base color.
            if (HitInfo.matIndex == -1) {
                if(skyColor == 1)
                {
                    float a = 0.5*(r.dir.y + 1);  
                    vec3 sky = (1-a)*vec3(1) + a * vec3(0.5, 0.7, 1.0);
                    rayColor = rayTraversalInfo * sky;  // environment brightness
                }
                break;
            }

            //Something got hit!
            vec3 HitPoint = r.pos + r.dir * HitInfo.dist;
            vec3 outwardN = HitInfo.normal;
            bool frontFace = dot(r.dir, outwardN) < 0.0;
            vec3 n = frontFace ? outwardN : -outwardN;
            material hitMat = materials[HitInfo.matIndex];



            r.pos = HitPoint + n * 0.001;
            r.dir = RandomCosineDir(seed, n);
            float brdf = ScatteringPdf(r.dir, n);
            float pdf = CosinePdf(r.dir, n);
            rayTraversalInfo *= hitMat.albedo * brdf/ pdf;

            rayColor += rayTraversalInfo * hitMat.emmColor;
        }
        finalColor += rayColor;
    }
    finalColor /= maxIter;

    imageStore(img, pix, vec4(sqrt(finalColor), 1.0));
}