#version 430 core
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D img;
const float pi = 3.14159265359;
const int maxBounces = 5;
const float INF = 3.402823466e+38;

struct ModelAABB
{
    vec4 min;
    vec4 max;
    int nodeA;
    int nodeB;
    int triIndex;
    int triCount;
};

//vec4 for good alignment
struct Triangle
{
    vec4 a;
    vec4 b;
    vec4 c;
    vec4 idtex;
};
//! add comments for the weird structure for triangle.



struct ModelInfo
{
    mat4 matrixModel;
    mat4 invMatrixModel;
    int matIndex;
};

struct MeshInfo
{
    int modelIdx;
    int textureIdx;
};
struct material
{
    int materialType;
    vec3 albedo;
    vec3 emmColor;
    float metallic;
    float roughness;
};
struct ray
{
    vec3 dir;
    vec3 pos;
};

struct hitInfo
{
    float dist;
    vec3 normal;
    int matIndex;
    vec3 color;
};

layout (binding = 4, std430) readonly buffer AABBIndices
{
    int ModelAABBIdxs[];
};
layout (binding = 3, std430) readonly buffer modelInfoData
{
    ModelInfo modelsInfo[];
};
layout (binding = 5, std430) readonly buffer meshInfoData
{
    MeshInfo meshInfo[];
};
layout (binding = 2, std430) readonly buffer AABBData
{
    ModelAABB aabbs[];
};

layout(binding = 1, std430) readonly buffer VerticesSSBO
{
    Triangle tris[];
};

//Scene Vars
uniform int modelAABBCount;
uniform float AR;
uniform float tfov;
uniform int uframe;
uniform vec3 CamPos;
uniform material materials[20];
uniform int TriCount;
uniform mat4 InvProj;
uniform mat4 InvView;
uniform sampler2D texImage[20];
uniform sampler2D skyTexture;

uint PCGHash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float RandomFloat(inout uint seed)
{
    seed = PCGHash(seed);
    return float(seed) / 4294967295.0;
}

vec3 RandomVec3(inout uint seed)
{
    return vec3(
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0);
}


vec3 SampleSquare(inout uint seed)
{
    return vec3(RandomFloat(seed) - 0.5,RandomFloat(seed) - 0.5,0.0); 
}

vec3 RandomOnHemisphere(inout uint seed, vec3 normal)
{
    vec3 vector = RandomVec3(seed);
    if(dot(vector, normal) > 0)
    {
        return vector;
    }else
    {
        return -vector;
    }
}


void hitTriangle(ray r, int i, inout hitInfo info)
{
    Triangle tri = tris[i];
    int curModelIdx = meshInfo[int(tri.idtex.x)].modelIdx;
    // r.pos = (modelsInfo[curModelIdx].invMatrixModel * vec4(r.pos, 1.0)).xyz;
    // r.dir = (modelsInfo[curModelIdx].invMatrixModel * vec4(r.dir, 0.0)).xyz;
    Triangle transformedTri;
    transformedTri.a = vec4(vec3(modelsInfo[curModelIdx].matrixModel * vec4(vec3(tri.a.x, tri.a.y, tri.a.z), 1.0)), tri.a.w);
    transformedTri.b = vec4(vec3(modelsInfo[curModelIdx].matrixModel * vec4(vec3(tri.b.x, tri.b.y, tri.b.z), 1.0)), tri.b.w);
    transformedTri.c = vec4(vec3(modelsInfo[curModelIdx].matrixModel * vec4(vec3(tri.c.x, tri.c.y, tri.c.z), 1.0)), tri.c.w);
    transformedTri.idtex = tri.idtex;
    tri = transformedTri;


    vec3 e1 = tri.b.xyz - tri.a.xyz;
    vec3 e2 = tri.c.xyz - tri.a.xyz;
    vec3 p = cross(r.dir, e2);
    float det = dot(e1, p);

    if(abs(det) < 1e-6) return;

    float invDet = 1.0 / det;
    vec3 t = r.pos - tri.a.xyz;
    float u = dot(t, p) * invDet;
    if(u < 0 || u > 1) return;

    vec3 q = cross(t, e1);
    float v = dot(r.dir, q) * invDet;
    if(v < 0 || u + v > 1) return;


    float dist = dot(e2, q) * invDet;
    if(dist > 0.001 && dist < info.dist)
    {
        info.dist = dist;
        info.normal = normalize(cross(e1, e2));
        info.matIndex = modelsInfo[int(tri.idtex.x)].matIndex;

        if(meshInfo[int(tri.idtex.x)].textureIdx != -1)
        {
            vec2 texCoordA = vec2(tri.a.w, tri.idtex.y);
            vec2 texCoordB = vec2(tri.b.w, tri.idtex.z);
            vec2 texCoordC = vec2(tri.c.w, tri.idtex.w);
            vec2 uvHit = (1-u-v)*texCoordA + u * texCoordB + v * texCoordC;
            info.color = texture(texImage[meshInfo[int(tri.idtex.x)].textureIdx], uvHit).rgb;
        }else
        {
            info.color = vec3(-1, -1, -1);
        }
    }
}
struct AABBHitInfo
{
    bool hit;
    float dist;
};
AABBHitInfo AabbRayIntersection(ray r, int idx)
{

    ModelAABB aabb = aabbs[idx];
    vec3 bmin = vec3(aabb.min);
    vec3 bmax = vec3(aabb.max);
    mat4 invModel = modelsInfo[int(aabb.min.w)].invMatrixModel;
    r.pos = (invModel * vec4(r.pos, 1.0)).xyz;
    r.dir = (mat3(invModel) * r.dir);

    vec3 invDir = 1.0 / r.dir;

    vec3 t0 = (bmin - r.pos) * invDir;
    vec3 t1 = (bmax - r.pos) * invDir;

    vec3 tmin = min(t0, t1);
    vec3 tmax = max(t0, t1);

    float tNear = max(max(tmin.x, tmin.y), tmin.z);
    float tFar  = min(min(tmax.x, tmax.y), tmax.z);
    float hitDistance = (tNear >= 0.0) ? tNear : tFar;
    AABBHitInfo genHitInfo;
    genHitInfo.hit = tFar >= max(tNear, 0.0);
    genHitInfo.dist = hitDistance;
    return genHitInfo;
}


const int STACK_SIZE = 16;


struct Stack {
    int data[STACK_SIZE];
    int sp; // stack pointer
};

void stackInit(inout Stack s) {
    s.sp = 0;
}

bool stackEmpty(Stack s) {
    return s.sp == 0;
}

bool stackPush(inout Stack s, int value) {
    if (s.sp >= STACK_SIZE) return false; // overflow
    s.data[s.sp++] = value;
    return true;
}

bool stackPop(inout Stack s, out int value) {
    if (s.sp <= 0) return false; // underflow
    value = s.data[--s.sp];
    return true;
}

void CheckAabbsIntersections(ray r, int starIdx, inout hitInfo HitInfo)
{
    Stack stack;
    stackInit(stack);
    stackPush(stack, starIdx);


    int aabbIdx;
    while(!stackEmpty(stack))
    {
        stackPop(stack, aabbIdx);
        AABBHitInfo reCheck = AabbRayIntersection(r, aabbIdx);
        if (reCheck.dist > HitInfo.dist)
        {
            continue; // Skip traversing this branch!
        }
        if(aabbs[aabbIdx].triCount == 0)
        {
            AABBHitInfo aHit = AabbRayIntersection(r, aabbs[aabbIdx].nodeA);
            AABBHitInfo bHit = AabbRayIntersection(r, aabbs[aabbIdx].nodeB);
            if(aHit.hit && bHit.hit)
            {
                if(aHit.dist < bHit.dist)
                {
                    stackPush(stack, aabbs[aabbIdx].nodeB);
                    stackPush(stack, aabbs[aabbIdx].nodeA);
                }else{
                    stackPush(stack, aabbs[aabbIdx].nodeA);
                    stackPush(stack, aabbs[aabbIdx].nodeB);
                }
            }
            else if(aHit.hit && !bHit.hit)
            {
                stackPush(stack, aabbs[aabbIdx].nodeA);
            }
            else if(bHit.hit && !aHit.hit)
            {
                stackPush(stack, aabbs[aabbIdx].nodeB);
            }
        }else
        {
            for(int i = aabbs[aabbIdx].triIndex; i < aabbs[aabbIdx].triIndex + aabbs[aabbIdx].triCount; i++)
            {
                hitTriangle(r, i, HitInfo);
            }
        }
    }
}

hitInfo GetHitInfoAABB(ray r)
{
    hitInfo HitInfo;
    HitInfo.dist = INF;
    HitInfo.matIndex = -1;
    for(int i = 0; i < modelAABBCount; i++)
    {
        CheckAabbsIntersections(r, ModelAABBIdxs[i], HitInfo);
    }
    return HitInfo;
}
hitInfo GetHitInfo(ray r)
{
    hitInfo HitInfo;
    HitInfo.dist = INF;
    HitInfo.matIndex = -1;
    for(int i = 0; i < TriCount; i++)
    {
        hitTriangle(r, i, HitInfo);
    }
    return HitInfo;
}

float ScatteringPdf(vec3 scatDir, vec3 n)
{
    float cosine = dot(scatDir, n);
    return cosine < 0 ? 0 : cosine / pi;
}


vec3 SampleSky(vec3 dir)
{
    float theta = atan(dir.z, dir.x);
    float phi =  asin(dir.y);

    float u = (theta + pi) / (2.0 * pi);
    float v = (phi + pi * 0.5) / pi;

    return texture(skyTexture, vec2(u,v)).rgb;
}


vec3 RandomCosineDir(inout uint seed, vec3 w)
{
    float r1 = RandomFloat(seed);
    float r2 = RandomFloat(seed);
    float z = sqrt(1-r2);
    float phi = 2 * pi * r1;
    float sqrtR2 = sqrt(r2);
    float x = cos(phi) * sqrtR2;
    float y = sin(phi) * sqrtR2;


    vec3 axis[3];
    axis[2] = normalize(w);
    vec3 a = (abs(axis[2].x) > 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1, 0, 0);
    axis[1] = normalize(cross(axis[2], a));
    axis[0] = cross(axis[2], axis[1]);

    return axis[0] * x + axis[1] * y + axis[2] * z; 
}

float CosinePdf(vec3 dir, vec3 n)
{
    float cosine = dot(normalize(dir), n);
    return max(0, cosine/ pi);
}

float GGXNDF(vec3 wm, float a)
{
    float costheta2 = wm.z * wm.z;
    float tantheta2 = -1.0 + 1.0 / costheta2;
    float denom = pi * costheta2 * costheta2 * pow((a*a + tantheta2), 2.0);
    return a*a / denom; 
}
vec3 Fresnel(vec3 wi, vec3 wm, vec3 f0)
{
    return f0 + (1-f0) * pow(1.0 -  dot(wi, wm), 5.0);
}
float lambda(vec3 w, vec3 n, float a)
{
    float costheta2 = dot(w, n);
    costheta2 *= costheta2;
    float tantheta2 = -1.0 + 1.0 / costheta2;
    return 0.5 * (sqrt(1.0 + a*a*tantheta2) - 1.0);
}
vec3 RandomWm(inout uint seed, vec3 w, float a)
{
    float r1 = RandomFloat(seed);
    float r2 = RandomFloat(seed);
    float thetam = atan(a * sqrt(r1 / (1 - r1)));
    float phim = 2 * pi * r2;
    float x = sin(thetam) * cos(phim);
    float y = sin(thetam) * sin(phim);
    float z = cos(thetam);


    vec3 axis[3];
    axis[2] = normalize(w);
    vec3 an = (abs(axis[2].x) > 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1, 0, 0);
    axis[1] = normalize(cross(axis[2], an));
    axis[0] = cross(axis[2], axis[1]);

    return axis[0] * x + axis[1] * y + axis[2] * z; 

}
float TorSpPdf(vec3 wo, vec3 wm, vec3 n, float a)
{
    float cosThetaM = max(dot(n, wm), 0.0);
    float cosWoWm = max(dot(wo, wm), 0.0);

    return GGXNDF(wm, a) * (cosThetaM) / (4.0 * cosWoWm);
}

float lightSamplingPdf(vec3 HitPoint, float area, vec3 wi)
{
    //!HARD CODED FOR CURRENT LIGHT QUAD.
    float t = (5.7 - HitPoint.y) / wi.y;

    if (t > 0.0) {
        vec3 intersectPos = HitPoint + t * wi;
        
        // Check if the intersection point lies within the quad's bounds [-0.35, 0.35]
        if (abs(intersectPos.x) <= 0.35 && abs(intersectPos.z) <= 0.35) {
            vec3 lightVec = intersectPos - HitPoint;
            return  dot(lightVec, lightVec) / (wi.y * area);
        }
    }
    return 0;
}
float G(vec3 wo, vec3 wi, vec3 n, float a)
{
    return (1 / (1 + lambda(wo,n, a) + lambda(wi,n, a)));
}




vec3 BRDFSampling(vec3 n,vec3 HitPoint, float area, vec3 f0, float a, vec3 wm, vec3 wi, vec3 wo,
inout vec3 rayTraversalInfo, vec3 matEmission)
{

    if(dot(wi, n) <= 0.0 || dot(wo, n) <= 0.0)
        return vec3(0);

    float NoV = max(dot(n, wo), 0.0);
    float NoL = abs(dot(n, wi));

    vec3 brdf = GGXNDF(wm, a)
            *Fresnel(wi, wm, f0)
            * G(wo, wi, n, a)
            / (4.0 * NoV * NoL);

    float pdfBrdf = TorSpPdf(wo, wm, n, a);
    float pdfLight = lightSamplingPdf(HitPoint, area, wi);
    float weight = pdfBrdf / (pdfBrdf + pdfLight);
    vec3 Sample = weight * brdf * NoL / pdfBrdf;
    return rayTraversalInfo *Sample* matEmission;
}

vec3 LightSampling(vec3 n, vec3 f0, float a, float area,
vec3 wm, vec3 wi, vec3 wo, vec3 HitPoint, inout vec3 rayTraversalInfo)
{
    ray rToLight;
    rToLight.pos = HitPoint + wi * 0.0001;
    rToLight.dir = wi;

    hitInfo HitInfo = GetHitInfoAABB(rToLight);
    if(HitInfo.matIndex == 5)
    {
        material hitMat = materials[HitInfo.matIndex];
        vec3 emmision = hitMat.emmColor;
        float NoV = max(dot(n, wo), 0.0);
        float NoL = abs(dot(n, wi));
        vec3 brdf = GGXNDF(wm, a)
            *Fresnel(wi, wm, f0)
            * G(wo, wi, n, a)
            / (4.0 * NoV * NoL);

        float pdfBrdf = TorSpPdf(wo, wm,n,a);
        float pdfLight = lightSamplingPdf(HitPoint, area, wi);
        float weight = pdfLight / (pdfBrdf + pdfLight);
        vec3 Sample = weight * brdf * NoL / (pdfLight);
        return (rayTraversalInfo*Sample * emmision);
    }
    return vec3(0);
}


void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(img);

    uint seed =
    uint(pix.x) * 1973u +
    uint(pix.y) * 9277u +
    uframe  * 26699u + 1u;
    vec3 offset = SampleSquare(seed);
    float u = (float(pix.x + offset.x) + 0.5) / float(size.x);
    float v = (float(pix.y + offset.y) + 0.5) / float(size.y);
    u = u * 2.0 - 1.0;
    v = v * 2.0 - 1.0;

    vec4 target = InvProj * vec4(u, v , 1.0, 1.0);

    ray r;
    r.dir = vec3(InvView * vec4(normalize(vec3(target) / target.w), 0));
    r.pos = CamPos;

    vec3 rayTraversalInfo = vec3(1.0);
    vec3 rayColor = vec3(0.0);
    for(int bounces = 0; bounces < maxBounces; bounces++)
    {

        hitInfo HitInfo = GetHitInfoAABB(r);
        // if nothing got hit, just return a base color.
        if (HitInfo.matIndex == -1) {
            // float a = 0.5*(r.dir.y + 1);  
            // vec3 sky = (1-a)*vec3(1) + a * vec3(0.5, 0.7, 1.0);
            // rayColor = rayTraversalInfo * sky;  // environment brightness
            // rayColor = rayTraversalInfo * SampleSky(normalize(r.dir));
            break;
        }

        //Something got hit.
        vec3 HitPoint = r.pos + r.dir * HitInfo.dist;
        vec3 outwardN = HitInfo.normal;
        bool frontFace = dot(r.dir, outwardN) < 0.0;
        vec3 n = frontFace ? outwardN : -outwardN;
        material hitMat = materials[HitInfo.matIndex];

        r.pos = HitPoint + n * 0.001;

        float a  = hitMat.roughness;
        vec3 wo = normalize(-r.dir);

        vec3 wm[2];
        vec3 wi[2];
        //Cook torrance pdf
        wm[0] = RandomWm(seed, n, a);
        wi[0] = -wo + 2.0 * dot(wo, wm[0]) * wm[0];


        //Light sampling
        float area = 0.7*0.7;
        vec3 pointOnLight = vec3((RandomFloat(seed) - 0.5) * 0.7, 5.7, (RandomFloat(seed) - 0.5) * 0.7);
        wi[1] = pointOnLight - HitPoint;
        wi[1] = normalize(wi[1]);
        // float distSqr = dot(wi[1], wi[1]);
        // float cosAng = wi[1].y;

        wm[1] = normalize(wi[1] + wo);
        if(HitInfo.color.r != -1)
        {
            hitMat.albedo = HitInfo.color;
        }

        vec3 f0 = hitMat.albedo;
        vec3 SampleSum = vec3(0);



        vec3 lightSample = LightSampling(n, f0, a, area, wm[1], wi[1], wo, HitPoint, rayTraversalInfo);
        vec3 brdfSample = BRDFSampling(n,HitPoint, area, f0, a, wm[0], wi[0], wo, rayTraversalInfo, hitMat.emmColor);
        
        rayColor += lightSample + brdfSample;

        float pdfBrdf = TorSpPdf(wo, wm[0], n, a);
        float NoL = abs(dot(n, wi[0]));
        vec3 brdf = GGXNDF(wm[0], a) * Fresnel(wi[0], wm[0], f0) * G(wo, wi[0], n, a) / (4.0 * max(dot(n, wo), 0.0) * NoL);

        rayTraversalInfo *= (brdf * NoL / pdfBrdf);
        r.dir = wi[0];
    }
    vec4 prev = imageLoad(img, pix);
    imageStore(img, pix, vec4(prev.rgb + rayColor, 1.0));
}