#version 430 core


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D imgAccum;

float pi = 3.14159265359;



/*
    Material type indeces.
    1 Lambertian
    2 Metal
    3 Dialectric
*/
//vec4 for good alignment
struct Triangle
{
    vec4 a;
    vec4 b;
    vec4 c;
};
layout(binding = 1, std430) readonly buffer VerticesSSBO
{
    Triangle tris[];
};

struct ModelInfo
{
    mat4 matrixModel;
    int matIndex;
};

struct material
{
    int materialType;
    vec3 albedo;
    vec3 emmColor;
    float fuzz;
    float refractionIndex;
};
struct sphere 
{
    vec3 point;
    float radius;
    int matIndex;
};
struct ray
{
    vec3 dir;
    vec3 pos;
};

struct hitInfo
{
    float dist;
    vec3 normal;
    int matIndex;
};


//Scene Vars
uniform ModelInfo modelsInfo[24];

uniform float AR;
uniform float tfov;
uniform vec3 CamPos;
uniform material materials[10];
uniform sphere Spheres[10];
uniform int TriCount;
uniform int SphereCount;
uniform mat4 InvProj;
uniform mat4 InvView;
uniform int frameIndex;
uniform int accumulate;
uniform int skyColor;


uint PCGHash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float RandomFloat(inout uint seed)
{
    seed = PCGHash(seed);
    return float(seed) / 4294967295.0;
}

vec3 RandomVec3(inout uint seed)
{
    return vec3(
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0);
}

vec3 RandomOnHemisphere(inout uint seed, vec3 normal)
{
    vec3 vector = RandomVec3(seed);
    if(dot(vector, normal) > 0)
    {
        return vector;
    }else
    {
        return -vector;
    }
}


vec3 RefractionScatter(vec3 Normal, vec3 IncomingRay, float refractionIndex) 
{ 
    // 1. Determine if we are entering or exiting the material
    bool frontFace = dot(IncomingRay, Normal) < 0.0; 
    float eta = frontFace ? (1.0 / refractionIndex) : refractionIndex; 
    
    vec3 unitDir = normalize(IncomingRay); 

    // 2. Use the built-in function
    vec3 refracted = refract(unitDir, Normal, eta);

    // 3. GLSL refract returns vec3(0.0) if total internal reflection occurs!
    if(refracted == vec3(0.0))
    {
        return reflect(unitDir, Normal);
    }
    
    return refracted; 
}

void hitSphere(ray r, int index, inout hitInfo info)
{
    sphere sphere = Spheres[index];
    vec3 Pc = r.pos-sphere.point;
    float b = dot(Pc, r.dir);
    float c = dot(Pc, Pc) - sphere.radius*sphere.radius;
    float Discr = b*b - c;

    if (Discr >= 0.0) {
        float s = sqrt(Discr);
        float t1 = -b - s;
        float t2 = -b + s;

        float t = (t1 > 0.001) ? t1 : t2;   // if inside, t1 is negative, use t2
        if (t > 0.001 && t < info.dist) {
            info.dist = t;
            vec3 HitPoint = r.pos + r.dir * t;
            info.normal = normalize(HitPoint - Spheres[index].point);
            info.matIndex = Spheres[index].matIndex;
        }
    }
}


void hitTriangle(ray r, int i, inout hitInfo info)
{
    Triangle tri = tris[i];

    Triangle transformedTri;
    transformedTri.a = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.a.x, tri.a.y, tri.a.z), 1.0)), tri.a.w);
    transformedTri.b = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.b.x, tri.b.y, tri.b.z), 1.0)), tri.a.w);
    transformedTri.c = vec4(vec3(modelsInfo[int(tri.a.w)].matrixModel * vec4(vec3(tri.c.x, tri.c.y, tri.c.z), 1.0)), tri.a.w);
    tri = transformedTri;
    vec3 e1 = tri.b.xyz - tri.a.xyz;
    vec3 e2 = tri.c.xyz - tri.a.xyz;
    vec3 p = cross(r.dir, e2);
    float det = dot(e1, p);

    if(abs(det) < 1e-6) return;

    float invDet = 1.0 / det;
    vec3 t = r.pos - tri.a.xyz;
    float u = dot(t, p) * invDet;
    if(u < 0 || u > 1) return;

    vec3 q = cross(t, e1);
    float v = dot(r.dir, q) * invDet;
    if(v < 0 || u + v > 1) return;

    float dist = dot(e2, q) * invDet;
    if(dist > 0.001 && dist < info.dist)
    {
        info.dist = dist;
        info.normal = normalize(cross(e1, e2));
        info.matIndex = modelsInfo[int(tri.a.w)].matIndex;
    }
}


hitInfo GetHitInfo(ray r)
{
    hitInfo HitInfo;
    HitInfo.dist = 1e30;
    HitInfo.matIndex = -1;
    for(int i = 0; i < SphereCount; i++)
    {
        hitSphere(r, i, HitInfo);
    }
    for(int i = 0; i < TriCount; i++)
    {
        hitTriangle(r, i, HitInfo);
    }
    return HitInfo;
}

float ScatteringPdf(vec3 scatDir, vec3 n)
{
    float cosine = dot(scatDir, n);
    return cosine < 0 ? 0 : cosine / pi;
}


vec3  RandomCosineDir(inout uint seed, vec3 w)
{
    float r1 = RandomFloat(seed);
    float r2 = RandomFloat(seed);
    float z = sqrt(1-r2);
    float phi = 2 * pi * r1;
    float sqrtR2 = sqrt(r2);
    float x = cos(phi) * sqrtR2;
    float y = sin(phi) * sqrtR2;


    vec3 axis[3];
    axis[2] = normalize(w);
    vec3 a = (abs(axis[2].x) > 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1, 0, 0);
    axis[1] = normalize(cross(axis[2], a));
    axis[0] = cross(axis[2], axis[1]);

    return axis[0] * x + axis[1] * y + axis[2] * z; 
}

float CosinePdf(vec3 dir, vec3 n)
{
    float cosine = dot(normalize(dir), n);
    return max(0, cosine/ pi);
}

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(imgAccum);

    float u = float(pix.x) / float(size.x);
    float v = float(pix.y) / float(size.y);

    u = u * 2.0 - 1.0;
    v = v * 2.0 - 1.0;

    vec4 target = InvProj * vec4(u, v , 1.0, 1.0);
    ray r;
    r.dir = vec3(InvView * vec4(normalize(vec3(target) / target.w), 0));
    r.pos = CamPos;

    

    vec3 rayTraversalInfo = vec3(1.0);
    vec3 rayColor = vec3(0.0);
    uint seed =
        uint(pix.x) * 1973u +
        uint(pix.y) * 9277u +
        frameIndex  * 26699u + 1u;

    for(int iter = 0; iter < 10; iter++)
    {

        hitInfo HitInfo = GetHitInfo(r);
        // if nothing got hit, just return a base color.
        if (HitInfo.matIndex == -1) {
            // if(skyColor == 1)
            // {
            //     float a = 0.5*(r.dir.y + 1);  
            //     vec3 sky = (1-a)*vec3(1) + a * vec3(0.5, 0.7, 1.0);
            //     rayColor = rayTraversalInfo * sky;  // environment brightness
            // }
            break;
        }

        //Something got hit!
        vec3 HitPoint = r.pos + r.dir * HitInfo.dist;
        vec3 outwardN = HitInfo.normal;
        bool frontFace = dot(r.dir, outwardN) < 0.0;
        vec3 n = frontFace ? outwardN : -outwardN;
        material hitMat = materials[HitInfo.matIndex];

        //Scatter light and evaluate color
        // vec3 randV = RandomOnHemisphere(seed, n); 
        // vec3 rNext = n + randV;


        // vec3 onLight = vec3(RandomFloat(seed) * 0.5 -0.25, 6.2, RandomFloat(seed)* 0.5 - 0.25);
        // vec3 toLight = onLight - HitPoint;
        // float distanceSqr = toLight.x*toLight.x + toLight.y*toLight.y + toLight.z*toLight.z;
        // toLight = normalize(toLight);


        // float lightArea = 1;
        // vec3 lightNormal = vec3(0.0, 1.0, 0.0);

        // float cosLight = max(dot(toLight, lightNormal), 0.0);

        r.pos = HitPoint + n * 0.001;
        r.dir = RandomCosineDir(seed, n);
        float brdf = ScatteringPdf(r.dir, n);
        float pdf = CosinePdf(r.dir, n);

    
        rayTraversalInfo *= hitMat.albedo * brdf/ pdf;

        rayColor += rayTraversalInfo * hitMat.emmColor;

    }
    if(accumulate == 1)
    {
        vec3 oldColor = imageLoad(imgAccum, pix).rgb;

        // clear accumulation texture on first frame
        if(frameIndex == 1)
            oldColor = vec3(0.0);

        vec3 newColor = oldColor + rayColor; // store sum
        imageStore(imgAccum, pix, vec4(newColor, 1.0));
    }else{
        imageStore(imgAccum, pix, vec4(rayColor, 1.0));
    }
}