#version 430 core


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D imgAccum;




uint PCGHash(uint InputSeed)
{
    uint state = InputSeed * 747796405u+2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 2778033737u;
    return (word >> 22u) ^ word;
}
float RandomFloat(inout uint seed){
    seed = PCGHash(seed);
    return float(seed) / 4294967295.0;
}

vec3 RandomInUnitSphere(inout uint seed){
    return normalize(vec3(
    RandomFloat(seed) * 2.0 - 1.0, 
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0));
}

uniform float AR;
uniform float tfov;
uniform vec3 CamPos;

//Scene Vars
uniform vec3 SPoint[10];
uniform float SRadius[10];
uniform float EmIntensity[10];
uniform vec3 Color[10];
uniform float mult[10];
uniform int SphereCount;
uniform int enableEnvironment;
uniform int FrameIndex;
uniform int accumalate;
void main()
{


    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(imgAccum);

    float u = (pix.x + 0.5) / size.x * 2.0 - 1.0;
    float v = (pix.y + 0.5) / size.y * 2.0 - 1.0;

    vec3 P = vec3(u * tfov * AR, v * tfov, 1.0);
    vec3 r = normalize(P);
    vec3 contribution = vec3(1.0);
    vec3 finalColor = vec3(0.0);
    vec3 StartPoint = CamPos;

    uint seed = uint(pix.x + pix.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x);
    seed *= FrameIndex;
    for(int iter = 0; iter < 7; iter++)
    {
        float nearestT = 1e30;
        int hitIndex = -1;
        for(int i = 0; i < SphereCount; i++)
        {
            vec3 Pc = StartPoint-SPoint[i];
            float Discr = (dot(Pc, r)*dot(Pc,r) - dot(Pc, Pc) + SRadius[i]*SRadius[i]);
            // float t = 0;
            if(Discr >= 0)
            {
                float t = -dot(Pc, r) - sqrt(Discr);
                if(t > 0.001 && t < nearestT)
                {
                    nearestT = t;
                    hitIndex = i;
                }
            }

        }
        if (hitIndex == -1 && enableEnvironment == 1) {
            finalColor += contribution * vec3(0.2, 0.2, 0.2);  // environment brightness
            break;
        }
        vec3 HitPoint = StartPoint + r * nearestT;
        vec3 Normal = normalize(HitPoint - SPoint[hitIndex]);
        StartPoint = HitPoint + Normal * 0.01;
        vec3 SpecularDir = reflect(r, Normal);
        StartPoint = StartPoint + Normal * 0.0001;
        vec3 DiiffuseDir = normalize(Normal + RandomInUnitSphere(seed));
        r = mix(DiiffuseDir, SpecularDir, mult[hitIndex]);

        finalColor += EmIntensity[hitIndex] * Color[hitIndex] * contribution;
        contribution *= Color[hitIndex];
    }
    vec3 newSample = finalColor;

    if (accumalate == 1 && FrameIndex > 1)
    {
        vec3 oldColor = imageLoad(imgAccum, pix).rgb;

        newSample = (oldColor * float(FrameIndex - 1) + newSample) 
                    / float(FrameIndex);
    }
    imageStore(imgAccum, pix, vec4(newSample, 1.0));
}