#version 430 core


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D imgAccum;


uniform float AR;
uniform float tfov;
uniform vec3 CamPos;


/*
    Material type indeces.
    1 Lambertian
    2 Metal
    3 Dialectric
*/



struct material
{
    int materialType;
    vec3 albedo;
    float fuzz;
    float refractionIndex;
};
struct sphere 
{
    vec3 point;
    float radius;
    int matIndex;
};

struct triangle
{
    int matIndex;
    vec3 a;
    vec3 b;
    vec3 c;
};

//Scene Vars
uniform material materials[10];
uniform sphere Spheres[10];
uniform triangle Triangles[30];
uniform int TriCount;
uniform int SphereCount;
uniform mat4 InvProj;
uniform mat4 InvView;
uniform int frameIndex;
uniform int accumulate;
uint PCGHash(uint seed)
{
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float RandomFloat(inout uint seed)
{
    seed = PCGHash(seed);
    return float(seed) / 4294967295.0;
}

vec3 RandomVec3(inout uint seed)
{
    return vec3(
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0,
    RandomFloat(seed) * 2.0 - 1.0);
}

vec3 RandomOnHemisphere(inout uint seed, vec3 normal)
{
    vec3 vector = RandomVec3(seed);
    if(dot(vector, normal) > 0)
    {
        return vector;
    }else
    {
        return -vector;
    }
}

vec3 LambertianScatter(vec3 Normal, inout uint seed)
{
    return Normal + RandomVec3(seed);
}

vec3 ReflectionScatter(vec3 Normal, vec3 IncomingRay, float fuzz, inout uint seed)
{
    vec3 reflected = normalize(reflect(IncomingRay, Normal)) + (fuzz * RandomVec3(seed));
    return reflected;
}

vec3 Refract(vec3 uv, vec3 n, float eta) 
{ 
    float cosTheta = min(dot(-uv, n), 1.0); 
    vec3 rPerp = eta * (uv + cosTheta*n); 
    vec3 rParral = -sqrt(abs(1.0 - length(rPerp)*length(rPerp))) * n; 
    return rPerp + rParral; 
} 
vec3 RefractionScatter(vec3 Normal, vec3 IncomingRay, float refractionIndex) 
{ 
    bool frontFace = dot(IncomingRay, Normal) < 0; 
    float ri = 0.0; 
    if(frontFace) 
    { 
        ri = (1.0 / refractionIndex); 
    }else { 
        ri = refractionIndex; 
    } 
    vec3 unitDir = normalize(IncomingRay); 

    float cosTheta = min(dot(-unitDir, Normal), 1.0);
    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);

    bool cannotRefract = (ri * sinTheta) > 1.0;
    vec3 direction;
    if(cannotRefract)
    {
        direction = reflect(unitDir, Normal);
    }else
    {
        direction = Refract(unitDir, Normal, ri);
    }

    vec3 refracted = direction; 
    return refracted; 
}

struct ray
{
    vec3 dir;
    vec3 pos;
};

struct hitInfo
{
    float dist;
    vec3 normal;
    int matIndex;
};

void hitSphere(sphere sphere, ray r, int index, inout hitInfo info)
{
    vec3 Pc = r.pos-sphere.point;
    float b = dot(Pc, r.dir);
    float c = dot(Pc, Pc) - sphere.radius*sphere.radius;
    float Discr = b*b - c;

    if (Discr >= 0.0) {
        float s = sqrt(Discr);
        float t1 = -b - s;
        float t2 = -b + s;

        float t = (t1 > 0.001) ? t1 : t2;   // if inside, t1 is negative, use t2
        if (t > 0.001 && t < info.dist) {
            info.dist = t;
            vec3 HitPoint = r.pos + r.dir * t;
            info.normal = normalize(HitPoint - Spheres[index].point);
            info.matIndex = Spheres[index].matIndex;
        }
    }
}


void hitTriangle(triangle tri, ray r, int index, inout hitInfo info)
{
    vec3 e1 = tri.b - tri.a;
    vec3 e2 = tri.c - tri.a;
    vec3 p = cross(r.dir, e2);
    float det = dot(e1, p);

    if(abs(det) < 1e-6) return;

    float invDet = 1.0 / det;
    vec3 t = r.pos - tri.a;
    float u = dot(t, p) * invDet;
    if(u < 0 || u > 1) return;

    vec3 q = cross(t, e1);
    float v = dot(r.dir, q) * invDet;
    if(v < 0 || u + v > 1) return;

    float dist = dot(e2, q) * invDet;
    if(dist > 0.001 && dist < info.dist)
    {
        info.dist = dist;
        info.normal = normalize(cross(e1, e2));
        info.matIndex = tri.matIndex;
    }
}

void main()
{


    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(imgAccum);

    float u = float(pix.x) / float(size.x);
    float v = float(pix.y) / float(size.y);

    u = u * 2.0 - 1.0;
    v = v * 2.0 - 1.0;

    vec4 target = InvProj * vec4(u, v , 1.0, 1.0);
    ray r;
    r.dir = vec3(InvView * vec4(normalize(vec3(target) / target.w), 0));
    r.pos = CamPos;

    

    vec3 contribution = vec3(1.0);
    vec3 finalColor = vec3(0.0);
    uint seed =
        uint(pix.x) * 1973u +
        uint(pix.y) * 9277u +
        frameIndex  * 26699u + 1u;;

    for(int iter = 0; iter < 10; iter++)
    {
        hitInfo HitInfo;
        HitInfo.dist = 1e30;
        HitInfo.matIndex = -1;
        for(int i = 0; i < SphereCount; i++)
        {
            hitSphere(Spheres[i],r, i, HitInfo);
        }
        for(int i = 0; i < TriCount; i++)
        {
            hitTriangle(Triangles[i],r, i, HitInfo);
        }


        if (HitInfo.matIndex == -1) {
            float a = 0.5*(r.dir.y + 1);  
            vec3 sky = (1-a)*vec3(1) + a * vec3(0.5, 0.7, 1.0);
            finalColor = contribution * sky;  // environment brightness
            break;
        }
        vec3 HitPoint = r.pos + r.dir * HitInfo.dist;
        vec3 outwardN = HitInfo.normal;
        bool frontFace = dot(r.dir, outwardN) < 0.0;
        vec3 n = frontFace ? outwardN : -outwardN;
        material hitMat = materials[HitInfo.matIndex];

        vec3 rNext = r.dir;

        if (hitMat.materialType == 1) {
            rNext = LambertianScatter(n, seed);
        } else if (hitMat.materialType == 2) {
            rNext = ReflectionScatter(n, r.dir, hitMat.fuzz, seed);
        } else if (hitMat.materialType == 3) {
            rNext = RefractionScatter(n, r.dir, hitMat.refractionIndex);
        }

        rNext = normalize(rNext);
        r.pos = HitPoint + rNext * 0.001;
        r.dir = rNext;

        contribution *= hitMat.albedo;
    }
    vec3 newColor = finalColor;

    if(accumulate == 1)
    {
        vec3 oldColor = imageLoad(imgAccum, pix).rgb;
        newColor = (oldColor * float(frameIndex - 1) + finalColor) / float(frameIndex);
    }

    imageStore(imgAccum, pix, vec4(newColor, 1.0));
}